name: MSBuild and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]
        platform: [x86, x64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} src/Dump1090.sln

      - name: Zip Artifacts
        run: |
          Compress-Archive -Path src/bin/${{ matrix.platform }}/${{ matrix.configuration }}/* -DestinationPath dump1090-${{ matrix.platform }}-${{ matrix.configuration }}.zip
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dump1090-${{ matrix.platform }}-${{ matrix.configuration }}
          path: dump1090-${{ matrix.platform }}-${{ matrix.configuration }}.zip

    release:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v3
          with:
            path: artifacts
   
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: v${{ github.event.inputs.version }}
            release_name: Release ${{ github.event.inputs.version }}
            draft: false
            prerelease: false
   
        - name: Upload Release Asset (x86)
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: artifacts/dump1090-x86-Release/dump1090-x86-Release.zip
            asset_name: dump1090-x86-Release.zip
            asset_content_type: application/zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
        - name: Upload Release Asset (x64)
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: artifacts/dump1090-x64-Release/dump1090-x64-Release.zip
            asset_name: dump1090-x64-Release.zip
            asset_content_type: application/zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
